plugins {
    id 'java'
    id 'application'
}

group = 'dev.varneth'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-core:2.13.4'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.4'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.4'
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'varneth.Main'
}

tasks.named('run', JavaExec) {
    standardInput = System.in
}