plugins {
    id 'java'
    id 'application'
}

group = 'dev.varneth'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

// Dein Code liegt direkt unter /src (nicht src/main/java)
sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

application {
    mainClass = 'Main'
}

tasks.named('run', JavaExec) {
    standardInput = System.in
}